### PR TITLE
Adjusted the InformationWeightTransformer 

### PR DESCRIPTION
**Pull request by cjweir**
The InformationWeightTransformer now scales by the expected idf factor of a token in a document given the idf factors associated to each 'topic' = log_2(P(token in doc))

### CODE REVIEW

**Comment by lmcinnes** [comment]
Tests are failing due to:

```
AttributeError: 'InformationWeightTransformer' object has no attribute 'expected_lengths_'
```

which seems to be a real error as far as I can tell. Shouldn't be too hard to fix.

**Comment by cjweir** [comment]
Fixed the naming error

**Comment by lmcinnes** [comment]
It's not throwing ZeroDivisionError in the PLSA. I'm not entirely sure why that should be or what has changed (since it worked preciously), but there are apparently still issues. Are there all zero rows being generated somehow?

**Comment by cjweir** [comment]
I can zero out a column if the token is in every document.  If a row only has such elements it could get set to zero

**Comment by cjweir** [comment]
I changed the test but I changed it back (the wrong way via 2 commits but it's done).  I figured the right thing was to set the minimal information weight to be epsilon ... basically deal with it Iike we did in other functions.

**Comment by lmcinnes** [comment]
Makes sense - -and I am kind of glad we had enough tests up to catch that case. I will definitely be happier when we have more robust testing in place.

**Pull request merged**
