### PR TITLE
Updated tokenizers to tokenize

### PR DESCRIPTION
**Pull request by cjweir**
by document (default) or by sentence (only if necessary).   I added / tweaked the basic tests as well and updated the DocVectorizer to handle the new tokenizer API.

### CODE REVIEW

**Comment by cjweir** [comment]
The issue seems to be importing stanza for the tests ... I'm not sure how to fix that.

**Comment by lmcinnes** [comment]
There are some yaml files for the different CI providers. You'll want to add stanza to one of the pip install lines in those. It should be obvious where (i.e. along with nltk and spacy).

**Comment by cjweir** [comment]
Seems like stanza wants pytorch and I can't get appveyor to get a versos to make it happy

**Comment by lmcinnes** [comment]
Drop the test that requires stanza then. pytorch can be a pain to make work well.

**Pull request merged**
