### PR TITLE
Adjusted transformers for hypothesis edge cases

### PR DESCRIPTION
**Pull request by cjweir**
Dealt with empty matrices and L1 normalized the matrix before pLSA to fix errors.

### CODE REVIEW

**Comment by cjweir** [comment]
On of the failures are hypothesis not able to generate test data.   The other may be from enstop needing something that might not be in an older version of python?

_../../../miniconda/envs/testenv/lib/python3.7/site-packages/textmap/transformers.py:7: in <module>
1218    import enstop
1219../../../miniconda/envs/testenv/lib/python3.7/site-packages/enstop/__init__.py:3: in <module>
1220    from enstop.block_parallel_plsa import BlockParallelPLSA
1221../../../miniconda/envs/testenv/lib/python3.7/site-packages/enstop/block_parallel_plsa.py:6: in <module>
1222    from sklearn.utils.validation import _check_sample_weight
1223E   ImportError: cannot import name '_check_sample_weight' from 'sklearn.utils.validation' (/home/travis/miniconda/envs/testenv/lib/python3.7/site-packages/sklearn/utils/validation.py)

**Comment by lmcinnes** [comment]
It's in a newer scikit-learn. I fixed that, but it might not be pushed up to PyPI yet. I've been playing with various things, so I don't quite have a super-stable version. It will get resolved in due course, so you can ignore those errors.

**Comment by acwooding** [comment]
A note on the scikit-learn version, you'll have to manually bump it up on the travis.yml file or it will continue to fail, as the python 3.7 version tests have SKLEARN_VERSION pegged to "0.20.3". It looks like the necessary scikit-learn version is in pypi as the 3.8 tests are automatically picking up a recent enough version to run successfully.

**Comment by cjweir** [comment]
I think all of the errors now are strange division by zeros in pLSA... outside of the sklearn version one anyways.

**Pull request merged**
